add ui.spec test
nooneMona/monachat-like pull request #40
Opened 2024-07-28 03:56 UTC by kisschan

uiテストを追加。

2024-07-28 04:45 UTC, nooneMona requested changes
PRありがとうございます。レビューしました。

2024-07-28 04:45 UTC, nooneMona commented on frontend/test/stores/ui.spec.ts
> +vi.mock("@/stores/setting", () => ({ useSettingStore }));
下記の通りに`createPinia`の代わりに`createTestingPinia`を使うことでモックできないですかね？
https://github.com/nooneMona/monachat-like/blob/265dadea82015303c24af5258eb1eda8ff55e5bb/frontend/test/components/atoms/SimpleButton.spec.ts#L50

2024-07-28 04:45 UTC, nooneMona commented on frontend/test/stores/ui.spec.ts
> +  it("backgroundColor should be return #d9d5da when isDarkMode is false", () => {
このあたりは`it.each`でまとめてもいいかもです。

2024-07-28 11:45 UTC, kisschan commented on frontend/test/stores/ui.spec.ts
> +vi.mock("@/stores/setting", () => ({ useSettingStore }));
確かにその通りですね

2024-07-28 11:46 UTC, kisschan commented on frontend/test/stores/ui.spec.ts
> +  it("backgroundColor should be return #d9d5da when isDarkMode is false", () => {
わかりました

2024-07-29 10:48 UTC, nooneMona approved these changes
ご対応ありがとうございます。明日の早朝にマージします。

2024-07-29 23:10 UTC, merged